### ISSUE TITLE
minor kerning & collisions between ALEF and LAM

### ISSUE THREAD

**Issue by mustafa0x** [DigitalKhatt/madinafont#2] opened 2023-03-26 03:10 UTC
large space in middle

![image](https://user-images.githubusercontent.com/1473102/227753039-75e740d1-2c2c-4f96-b512-8a383b56fadd.png)

---

needs more space after إ
![image](https://user-images.githubusercontent.com/1473102/227753080-0854be6d-e2de-4baf-8918-279975dfc2d9.png)

**Comment by aminanan** [comment] 2023-04-05 00:43
I committed a new file with the following changes.
![Untitled](https://user-images.githubusercontent.com/33678118/229952594-9775c3c1-9962-4eda-b90f-2f03992c5c45.png)

**Comment by mustafa0x** [comment] 2023-04-05 04:16
very nice. if you don't mind I think i'll leave this open in case I notice anything else.

**Comment by munzirtaha** [comment] 2023-04-20 02:30
There is still inconsistency here. Kerning should be the same with all types of ALEF irrespective of the letter following LAM
![alef](https://user-images.githubusercontent.com/2936425/233241964-8a4e9d42-988a-4621-854a-ef5ba01f83ef.png)

**Comment by aminanan** [comment] 2023-06-16 07:50
Is this Ok ?
<img width="665" alt="Capture" src="https://github.com/DigitalKhatt/madinafont/assets/33678118/301d553c-d305-4cb0-b1f3-a9ccdb716d5e">

**Comment by munzirtaha** [comment] 2023-06-16 09:33
It's much better now. However, in https://qurancomplex.gov.sa/kfgqpc-quran-hafs-mumtaz, I see the hamza is aligned with the sukun which makes it nicer.
![ألفوا](https://github.com/DigitalKhatt/madinafont/assets/2936425/9d527c89-f42e-43fc-b460-051348ad66a1)

**Comment by aminanan** [comment] 2023-06-22 14:08
I changed the title to be specific to the LAM ALEF kerning error, so I can close the issue. If you have any other problem regarding this LAM ALEF kerning, please re-open the issue. For another problem, please create a new issue.

**Comment by munzirtaha** [comment] 2023-06-25 16:02
Reopen please, because there is a regression here, e.g.

<img src="https://github.com/DigitalKhatt/madinafont/assets/2936425/c654d85c-bd2d-41ef-9783-d63cc5f3601b" width="100" />

**Closed as completed** 2023-06-26 22:02 UTC

**Comment by aminanan** [comment] 2023-06-26 22:04
<img width="794" alt="Capture" src="https://github.com/DigitalKhatt/madinafont/assets/33678118/211a20dd-b1a7-4003-963b-ffc884a40e69">
